### PR TITLE
Added all fixes

### PR DESCRIPTION
**Pull request by pupubird**

### CODE REVIEW

**Comment by pupubird** [comment]
@easonchai :c

**Comment by easonchai** [comment]
Let me know if this works, can't merge anything without messing up the code for others 🙁

**Review by easonchai — APPROVED** [review]
I'm curious, did you notice this happening when running the code or by reading? 😂

**Review by easonchai — APPROVED** [review]
Wow! 😱 👏

**Review by easonchai — COMMENTED** [review]
I think you're literally the only one who did this 😂

**Comment by pupubird** [comment]
Hahahaha thanks!
XD It's a good challenge, Kudo!
Some of them are through reading, but most of them test out in the run-time haha XD
Thanks!

**Comment by pupubird** [comment]
:O it does works! Created without messing the base

**Review by pupubird — COMMENTED** [review]
hrm

**Pull request closed without merging**
